### ISSUE TITLE
Pretty print leaves extra space at end of many lines

### ISSUE THREAD

**Issue by hazendaz** [jhy/jsoup#1689]
This one demonstrates far easier.  At end of most lines, there is an extra whitespace being added.  This should be trimmed so there is no extra whitespace at end of tags. 

Saved https://try.jsoup.org/~pWWgM1Tq8l3YM1WTm8Fftq5ziv4

**Comment by damienhunter30** [comment]
A fix can either be added to the code, or if you're doing in yourself you could add `"String".stripTrailing()` to remove the trailing whitespace from a string.

**Comment by hazendaz** [comment]
we have it fixed on our end but prefer its fixed in the source of the issue.

Here is how.

```
/** The Constant REMOVE_TRAILING_PATTERN. */
private static final Pattern REMOVE_TRAILING_PATTERN = Pattern.compile("\\p{Blank}+$", Pattern.MULTILINE);
...
// Fixing trailing space issue caused by jsoup
formattedCode = REMOVE_TRAILING_PATTERN.matcher(formattedCode).replaceAll("");
```

**Comment by damienhunter30** [comment]
I'll plug this in and see if I can get my first commit accepted.

**Comment by jhy** [comment]
Thanks! Have fixed this by checking in TextNode if the node is just a newline + empties, which can be safely whitespace normalized away. Effectively, this means if the parent element created an indent, if this TextNode (on re-parse) is the content of that indent, we should skip it.

This is a relatively new issue - in earlier versions of jsoup, these TextNodes (\n\s+) would have been dropped during parsing. We changed that to better preserve content when pretty printing was disabled, but that caused this knock-on impact.

**Comment by jhy** [comment]
@hazendaz, can you please verify these pretty print issues are fixed (with a snapshot install)? LMK if there are outstanding issues. Thanks!

**Comment by hazendaz** [comment]
This one is not fixed based on lastest master.  Have tested multiple times in last hour or so.  To fix this, the snippet of code I showed earlier is still needed to patch externally after formatting is done.

**Comment by hazendaz** [comment]
@jhy Is it possible you can release out a release candidate or if you are ready just cut a release?  We are significantly behind on the formatter plugin with fixes in this release with tabbing limits so unable to at least push up a test there that is coherent with latest codebase.  A release candidate or full release will help.  My outstanding issues are far less important even if a release were to occur as they already existed for some time.  Our tests are running 2 passes on all file types to ensure both times formatting processes that it is the same result.  The extra space issue here I have a patch on our end for it which I can use to get around this one.  The other two PRs I have outstanding while ideal to have fixed they don't harm processing (just not perfect).  I'm fine with the other issues moving to subsequent release given my main issue was the <script> tag that kept getting new lines is now fixed.  The others do not cause unexpected side affects.

**Comment by jhy** [comment]
@hazendaz sure - I'm not ready with a release yet, but I deployed a snapshot RC. You should be able to grab it with

```xml
<dependency>
  <groupId>org.jsoup</groupId>
  <artifactId>jsoup</artifactId>
  <version>1.15.1-SNAPSHOT</version>
</dependency>
```
It may take a moment to sync to the Central Maven Repo after publishing. Delivery repo is at https://oss.sonatype.org/content/repositories/snapshots/org/jsoup/jsoup/1.15.1-SNAPSHOT/jsoup-1.15.1-20220103.051042-1.jar

I plan to do a full release shortly (next week or so).

**Comment by jhy** [comment]
> This one is not fixed based on lastest master. Have tested multiple times in last hour or so. To fix this, the snippet of code I showed earlier is still needed to patch externally after formatting is done.

Hmm - there must be another instance of it coming from somewhere. I certainly fixed a set of issues where on repeat serialize -> parse -> serialize, extra spaces were added after closing tags (coming from a "\n  " getting normalized to a " " text output. Examples are in the changed testcases, was appearing on head, body etc.

Will take another pass at your testcase.

**Comment by hazendaz** [comment]
Can you reopen this one?  This is now in our 'main' at https://github.com/revelc/formatter-maven-plugin, just run 'mvn clean install', then go to target/testoutput/someFile.html.  Look at trailing spaces left throughout.  While we have code that has expanded our ability to trim whitespace that now entirely resolves this for end users, it would be nice to fix in proper location.

**Comment by hazendaz** [comment]
@jhy Even though not all fixed, is it possible we can get a release out as-is?  Its at least a good improvement for us and we need to get ours released soon and I'd prefer not to drop back off the current snapshot as that requires us go back multiple versions.

**Comment by hazendaz** [comment]
@jhy Or if not 100% with what you wanted, can you release a milestone?

**Comment by spincast** [comment]
I'm interested in a stable version containing this fix too. My tests failed because of this issue.

**Comment by electrotype** [comment]
I'd be interested in a stable version containing this fix too. My tests failed because of this issue.

**Comment by henrykuijpers** [comment]
@jhy  I just bumped into this issue as well and I was baffled to find out that the resulting document contains "random?" spaces added to the closing tags of elements etc. There doesn't seem to be a logical pattern. I also noticed that with another input file, which literally contains the same HTML content, this didn't happen. There must be something going on with the parsing of linefeed / carriage returns / ... I was also able to somehow let Jsoup output (literally) `\r` in the resulting document (instead of a carriage return, so probably somewhere the `\` was escaped?

Would be nice to get some fixes for this. :)
